config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :searches, only: [:index ]
  get 'search', to: 'searches#show'

  root 'searches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


  def index
  end

  def show
    @query = params[:query]
    @city = params[:city]
    @state = params[:state]
    respond_to do |format|
      if params[:dice]
        diceResponse = ApiService::Dice.new(@query, @city, @state)
        @dice = diceResponse.get_dice
        format.js { render 'dice' }
      elsif params[:indeed]
        indeedResponse = ApiService::Indeed.new(@query, @city, @state)
        @indeed = indeedResponse.get_indeed
        format.js { render 'indeed' }
      elsif params[:glassdoor]
        glassdoorResponse = ApiService::Glassdoor.new(@query, @city, @state)
        @glassdoor = glassdoorResponse.get_glassdoor
        format.js { render 'glassdoor' }
      elsif params[:github]
        githubResponse = ApiService::Github.new(@query, @city, @state)
        @github = githubResponse.get_github
        format.js { render 'github' }
      else
        format.html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Search</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Welcome to Job Search", searches_path, class: 'navbar-brand' %>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <%= current_user.email %></li>
              <%= link_to "Log-out", destroy_user_session_path, method: "delete", class: 'navbar-brand' %>
            <% else %>
              <%= link_to "Log-in", new_user_session_path, class: 'navbar-brand' %></a>
               <%= link_to "Signup", new_user_registration_path, class: 'navbar-brand' %></a>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
        <div class="container">
          <div class="alert-warning">
          <%= flash[:alert] %>
          <%= flash[:notice] %>
        </div>
        <div class="form-area">

          <%= render 'form' %>
          <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/searches/_dice.html.erb
<div class="job-box pre-scrollable panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title">Dice.com results:</h2>
  </div>
  <div class="panel-body">
    <% @dice.each do |d| %>
    Company: <%= d["company"] %>, <%= d["location"]  %><br>
    Job Title: <%= link_to d["jobTitle"], d["detailUrl"] %><br>
    Posted <%= time_ago_in_words(d["date"]) %> ago
    <hr>
    <% end %>
  </div>
</div>

app/views/searches/_form.html.erb
<div class="form-section">
    <%= form_tag(search_path, :method => "get", class: 'form-horizontal') do %>
    <fieldset>
      <legend>Search for Jobs</legend>
    <div class="form-group">
      <%= label_tag(:query,'Keyword', class: 'col-lg-2 control-label') %>
      <div class="col-lg-10">
        <%= text_field_tag 'query', nil, required: true, class: 'form-control', placeholder: 'Job Title, Skill, etc.'  %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag(:city,'City', class: 'col-lg-2 control-label') %>
      <div class="col-lg-10">
        <%= text_field_tag 'city', nil, required: true, class: 'form-control' , placeholder: 'City' %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag(:state,'State', class: 'col-lg-2 control-label') %>
      <div class="col-lg-10">
        <%= select_tag(:state, options_for_select([['Alabama', 'AL'], ['Alaska', 'AK'], ['Arizona', 'AZ'], ['Arkansas', 'AR'], ['California', 'CA'], ['Colorado', 'CO'], ['Connecticut', 'CT'], ['Delaware', 'DE'], ['Florida', 'FL'], ['Georgia', 'GA'], ['Hawaii', 'HI'], ['Idaho', 'ID'], ['Illinois', 'IL'], ['Indiana', 'IN'], ['Iowa', 'IA'], ['Kansas', 'KS'], ['Kentucky', 'KY'], ['Louisana', 'LA'], ['Maine', 'ME'], ['Maryland', 'MD'], ['Massachusetts', 'MA'], ['Michigan', 'MI'], ['Minnesota', 'MN'], ['Mississippi', 'MS'], ['Missouri', 'MO'], ['Montana', 'MT'], ['Nebraska', 'NE'], ['Nevada', 'NV'], ['New Hampshire', 'NH'], ['New Jersey', 'NJ'], ['New Mexico', 'NM'], ['New York', 'NY'], ['North Carolina', 'NC'], ['North Dakota', 'ND'], ['Ohio', 'OH'], ['Oklahoma', 'OK'], ['Oregon', 'OR'], ['Pennsylvania', 'PA'], ['Rhode Island', 'RI'], ['South Carolina', 'SC'], ['South Dakota', 'SD'], ['Tennessee', 'TN'], ['Texas', 'TX'], ['Utah', 'UT'], ['Vermont', 'VT'], ['Virginia', 'VA'], ['Washingotn', 'WA'], ['West Virginia', 'WV'], ['Wisconsin', 'WI'], ['Wyoming', 'WY']]), class: 'select_box') %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= submit_tag("Search", class: 'btn btn-success') %>
        <button type="reset" class="btn btn-danger">Clear</button>
      </div>
    </div>
  </fieldset>
  <% end %>
</div>

app/views/searches/_github.html.erb
<div class="job-box pre-scrollable panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Github.com results:</h2>
  </div>
  <div class="panel-body">
    <% if @github.any? %>
      <% @github.each do |g| %>
      Company: <%= g["company"] %>, <%= g["location"]  %><br>
      Job Title: <%= link_to g["title"], g["url"] %>
      <hr>
      <% end %>
    <% else %>
      <p>
        There are no results.
      </p>
    <% end %>
  </div>
</div>

app/views/searches/_glassdoor.html.erb
<div class="job-box pre-scrollable panel panel-warning">
  <div class="panel-heading">
    <h2 class="panel-title">Glassdoor.com results:</h2>
  </div>
  <div class="panel-body">
    <% @glassdoor.each do |g| %>
    Location: <%= g["name"] + ' - ' %>
    Job Postings: <%= link_to g["numJobs"], "https://www.glassdoor.com/Job/jobs.htm?typedKeyword=" + @query + "&sc.keyword=" + @query + "&locT=C&locId=" + g['id'].to_s %>
    <hr>
    <% end %>
  </div>
</div>

app/views/searches/_indeed.html.erb
<div class="job-box pre-scrollable panel panel-info">
  <div class="panel-heading">
    <h2 class="panel-title">Indeed.com results:</h2>
  </div>
  <div class="panel-body">
    <% @indeed.each do |i| %>
    Company: <%= i["company"] %>, <%= i["formattedLocation"] %><br>
    Job Title: <%= link_to i["jobtitle"], i["url"] %><br>
    Description: <%= i["snippet"] %><br>
    Posted <%= i["formattedRelativeTime"] %>
    <hr>
    <% end %>
  </div>
</div>

app/views/searches/dice.js.erb
$('.job-section').empty();
$('.job-section').html('<%= j render "dice" %>');

app/views/searches/github.js.erb
$('.job-section').empty();
$('.job-section').html('<%= j render "github" %>');

app/views/searches/glassdoor.js.erb
$('.job-section').empty();
$('.job-section').html('<%= j render "glassdoor" %>');

app/views/searches/indeed.js.erb
$('.job-section').empty();
$('.job-section').html('<%= j render "indeed" %>');

app/views/searches/show.html.erb
<ul class="nav nav-pills">
  <li id="dice"><a><%= link_to "Dice", search_path(dice: true, query: @query, city: @city, state: @state), remote: true, class: 'btn btn-primary' %></a></li>
  <li id="github"><a><%= link_to "Github", search_path(github: true, query: @query, city: @city, state: @state), remote: true, class: 'btn btn-default' %></a></li>
  <li id="glassdoor"><a><%= link_to "Glassdoor", search_path(glassdoor: true, query: @query, city: @city, state: @state), remote: true, class: 'btn btn-warning' %></a></li>
  <li id="indeed"><a><%= link_to "Indeed", search_path(indeed: true, query: @query, city: @city, state: @state), remote: true, class: 'btn btn-info' %></a></li>
</ul>
<div class="row job-section">

</div>